// Run with Figma MCP use_figma. This builds editable layers, never a UI image.
const page = await figma.getNodeByIdAsync('0:1');
await figma.setCurrentPageAsync(page);
await Promise.all(['Regular', 'Medium', 'Semibold', 'Bold'].map(style => figma.loadFontAsync({ family: 'SF Pro', style })));
if (page.children.some(n => n.name === 'Return Queue / Prototype v1')) throw new Error('Board already exists; inspect it before updating.');
const created = [], remember = n => { created.push(n.id); return n; };
// Adapted from the bundled createVariableCollection helper.
async function createVariableCollection(name, modes) {
  const collection = figma.variables.createVariableCollection(name), modeIds = {};
  collection.renameMode(collection.modes[0].modeId, modes[0]); modeIds[modes[0]] = collection.modes[0].modeId;
  for (let i = 1; i < modes.length; i++) modeIds[modes[i]] = collection.addMode(modes[i]);
  return { collection, modeIds };
}
const { collection, modeIds } = await createVariableCollection('Return Queue / Foundations', ['Light']);
const vars = {}, colors = { canvas:'#E9ECF2', background:'#F5F6FA', surface:'#FFFFFF', ink:'#18213B', secondary:'#5D6880', accent:'#3155CB', tint:'#EBEFFE', line:'#E5E8F0', warning:'#9A4C12', warningBg:'#FFF3E7', success:'#23755A', successBg:'#E8F5EE', danger:'#B53841' };
const rgb = hex => ({r:parseInt(hex.slice(1,3),16)/255,g:parseInt(hex.slice(3,5),16)/255,b:parseInt(hex.slice(5,7),16)/255});
for (const [name, hex] of Object.entries(colors)) {
  const primitive = figma.variables.createVariable('primitive/'+name, collection, 'COLOR'); primitive.scopes=[]; primitive.setValueForMode(modeIds.Light, {...rgb(hex),a:1});
  const v = figma.variables.createVariable('color/'+name, collection, 'COLOR'); v.scopes=['FRAME_FILL','SHAPE_FILL','TEXT_FILL','STROKE_COLOR']; v.setValueForMode(modeIds.Light, {type:'VARIABLE_ALIAS',id:primitive.id}); v.setVariableCodeSyntax('iOS','ReturnQueueTheme.'+name); vars[name]=v;
}
for (const v of [4,8,12,16,20,24,32,40]) {const token=figma.variables.createVariable('spacing/'+v,collection,'FLOAT');token.scopes=['GAP'];token.setValueForMode(modeIds.Light,v);token.setVariableCodeSyntax('iOS','ReturnQueueSpacing.s'+v);vars['s'+v]=token;}
for (const v of [12,16,20,28]) {const token=figma.variables.createVariable('radius/'+v,collection,'FLOAT');token.scopes=['CORNER_RADIUS'];token.setValueForMode(modeIds.Light,v);token.setVariableCodeSyntax('iOS','ReturnQueueRadius.r'+v);vars['r'+v]=token;}
const paint = name => figma.variables.setBoundVariableForPaint({type:'SOLID',color:rgb(colors[name])},'color',vars[name]);
const styles = {};
for (const [name,size,weight,line] of [['large',32,'Bold',38],['title',26,'Bold',32],['heading',20,'Semibold',25],['body',17,'Regular',23],['strong',17,'Semibold',23],['subhead',15,'Medium',20],['caption',13,'Regular',18],['micro',11,'Semibold',15]]) {
  const s=figma.createTextStyle();s.name='Return Queue/'+name;s.fontName={family:'SF Pro',style:weight};s.fontSize=size;s.lineHeight={unit:'PIXELS',value:line};styles[name]=s;
}
function box(parent,name,direction='VERTICAL',width=353,gap=12,fill=null,pad=0,radius=0) {
  const n=remember(figma.createAutoLayout(direction));n.name=name;n.fills=fill?[paint(fill)]:[];n.resize(width,1);n.primaryAxisSizingMode=direction==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=direction==='VERTICAL'?'FIXED':'AUTO';n.itemSpacing=gap;if(vars['s'+gap])n.setBoundVariable('itemSpacing',vars['s'+gap]);
  for(const p of ['paddingTop','paddingBottom','paddingLeft','paddingRight']){n[p]=pad;if(vars['s'+pad])n.setBoundVariable(p,vars['s'+pad]);}if(radius){n.cornerRadius=radius;if(vars['r'+radius])n.setBoundVariable('cornerRadius',vars['r'+radius]);}
  if(parent)parent.appendChild(n);return n;
}
async function text(parent,copy,role='body',color='ink',width=null) {
  const n=remember(figma.createText());n.name=copy;n.fontName=styles[role].fontName;await n.setTextStyleIdAsync(styles[role].id);n.characters=copy;n.fills=[paint(color)];n.textAutoResize=width?'HEIGHT':'WIDTH_AND_HEIGHT';if(width)n.resize(width,n.height);parent.appendChild(n);return n;
}
const paths={package:'<path d="M3 7l9-5 9 5v10l-9 5-9-5V7zm0 0l9 5 9-5M12 12v10M7.5 4.5l9 5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',history:'<path d="M3 10a9 9 0 1 1 2 8M3 4v6h6M12 7v5l3 2"/>',settings:'<path d="M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3Z"/><circle cx="12" cy="12" r="3"/>',plus:'<path d="M12 5v14M5 12h14"/>',chevron:'<path d="m9 5 7 7-7 7"/>',back:'<path d="m15 5-7 7 7 7"/>',check:'<path d="m5 12 4 4L19 6"/>',money:'<rect x="2" y="5" width="20" height="14" rx="3"/><circle cx="12" cy="12" r="3"/><path d="M6 12h.01M18 12h.01"/>',credit:'<rect x="2" y="4" width="20" height="16" rx="3"/><path d="M2 9h20M6 15h4"/>',archive:'<path d="M4 8h16v13H4V8Z"/><rect x="2" y="3" width="20" height="5" rx="1"/><path d="M9 12h6"/>',shield:'<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6l-9-4Z"/><path d="m8 12 3 3 5-6"/>',export:'<path d="M12 15V2m-4 4 4-4 4 4M4 10v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V10"/>',restore:'<path d="M12 2v13m-4-4 4 4 4-4M4 14v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-6"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="3"/>'};
function icon(parent,name,color='ink',size=22){const n=remember(figma.createNodeFromSvg('<svg width="'+size+'" height="'+size+'" viewBox="0 0 24 24" fill="none" stroke="'+colors[color]+'" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" xmlns="http://www.w3.org/2000/svg">'+paths[name]+'</svg>'));n.name='Icon/'+name;parent.appendChild(n);for(const v of n.findAll(()=>true)){created.push(v.id);if('strokes'in v&&Array.isArray(v.strokes)&&v.strokes.length)v.strokes=v.strokes.map(p=>p.type==='SOLID'?figma.variables.setBoundVariableForPaint(p,'color',vars[color]):p);}return n;}
const library=box(page,'Return Queue / Local components','VERTICAL',500,24,'background',24,20);library.x=2050;library.y=80;await text(library,'Reusable components','heading');await text(library,'Local components · SF Pro · Light theme','caption','secondary');
const components={}, props={};
async function component(name,build){const frame=box(null,name,'VERTICAL',353,8,'surface',16,20);await build(frame);library.appendChild(frame);const c=remember(figma.createComponentFromNode(frame));c.name='Return Queue/'+name;c.description='Editable '+name+' used in the Return Queue free iPhone prototype.';components[name]=c;props[name]={};for(const t of c.findAllWithCriteria({types:['TEXT']})){const p=c.addComponentProperty(t.name,'TEXT',t.characters);t.componentPropertyReferences={characters:p};props[name][t.name]=p;}return c;}
function use(parent,name,values={}){const c=components[name],n=remember(c.createInstance());n.name=name;parent.appendChild(n);if(c.layoutMode!=='NONE')n.layoutSizingHorizontal='FILL';n.setProperties(Object.fromEntries(Object.entries(values).map(([k,v])=>[props[name][k],v])));for(const d of n.findAll(()=>true))created.push(d.id);return n;}
await component('Return card',async f=>{f.paddingTop=12;f.paddingBottom=12;const r=box(f,'Item and merchant','HORIZONTAL',321,12);const col=box(r,'Item labels','VERTICAL',283,4);await text(col,'Item name','strong');await text(col,'Merchant','caption','secondary');icon(r,'chevron','secondary',18);const bottom=box(f,'Date and amount','HORIZONTAL',321,8);await text(bottom,'Return date','caption','accent',181);const amount=await text(bottom,'Expected amount','caption','secondary',132);amount.textAlignHorizontal='RIGHT';});
await component('Field',async f=>{f.paddingTop=12;f.paddingBottom=12;f.cornerRadius=16;f.setBoundVariable('cornerRadius',vars.r16);await text(f,'Field label','caption','secondary');await text(f,'Field value','body');});
await component('Info row',async f=>{f.paddingTop=8;f.paddingBottom=8;f.layoutMode='HORIZONTAL';f.counterAxisAlignItems='CENTER';await text(f,'Row label','subhead','secondary',190);const t=await text(f,'Row value','strong', 'ink',115);t.textAlignHorizontal='RIGHT';});
await component('Action',async f=>{f.layoutMode='HORIZONTAL';f.primaryAxisAlignItems='CENTER';f.counterAxisAlignItems='CENTER';f.paddingTop=14;f.paddingBottom=14;f.fills=[paint('accent')];await text(f,'Action label','strong','surface');});
await component('Secondary action',async f=>{f.layoutMode='HORIZONTAL';f.primaryAxisAlignItems='CENTER';f.counterAxisAlignItems='CENTER';f.paddingTop=14;f.paddingBottom=14;f.fills=[paint('tint')];await text(f,'Action label','strong','accent');});
await component('History card',async f=>{f.paddingTop=12;f.paddingBottom=12;await text(f,'History item','strong');await text(f,'History merchant','caption','secondary');await text(f,'History outcome','subhead','success');await text(f,'History amounts','caption','secondary');});
await component('Reimbursement',async f=>{f.paddingTop=12;f.paddingBottom=12;const row=box(f,'Amount and type','HORIZONTAL',321,12);icon(row,'money','accent');await text(row,'Reimbursement type','strong', 'ink',183);await text(row,'Reimbursement amount','strong');await text(f,'Reimbursement date','caption','secondary');});
const board=box(page,'Return Queue / Prototype v1','VERTICAL',1800,32,'canvas',48,28);board.x=80;board.y=80;
await text(board,'RETURN QUEUE  /  IPHONE PROTOTYPE','micro','accent');await text(board,'Less to remember. More returned.','large');await text(board,'A free, local return journal. Demo amounts and dates are entered by the user.','body','secondary');
const screens={}, links=[], rows=[box(board,'01 / Return workflow','HORIZONTAL',1704,32),box(board,'02 / Money and records','HORIZONTAL',1704,32)];
const status=await component('Status bar',async f=>{f.resize(393,54);f.paddingLeft=28;f.paddingRight=28;f.paddingTop=16;f.paddingBottom=14;f.fills=[];f.layoutMode='HORIZONTAL';f.itemSpacing=212;await text(f,'9:41','subhead');await text(f,'•••  ▰','caption');});
async function phone(key,label,rowIndex){const cell=box(rows[rowIndex],label,'VERTICAL',393,12);await text(cell,label,'micro','secondary');const f=box(cell,key,'VERTICAL',393,0,'background',0);f.resize(393,852);f.primaryAxisSizingMode='FIXED';f.cornerRadius=40;f.clipsContent=true;f.strokes=[paint('line')];f.strokeWeight=1;f.effects=[{type:'DROP_SHADOW',color:{r:0.07,g:0.12,b:0.25,a:0.09},offset:{x:0,y:10},radius:24,spread:0,visible:true,blendMode:'NORMAL'}];screens[key]=f;use(f,'Status bar');const c=box(f,'Content','VERTICAL',393,16,null,20);c.paddingTop=0;c.paddingBottom=16;c.layoutSizingVertical='FILL';return {f,c};}
async function nav(c,left,right,title=null){const n=box(c,'Navigation','HORIZONTAL',353,12);n.counterAxisAlignItems='CENTER';if(left){const l=box(n,'Back','HORIZONTAL',240,4);icon(l,'back','accent',18);await text(l,left,'subhead','accent');links.push([l,'Queue']);}else await text(n,'YOUR RETURN JOURNAL','micro','secondary',295);if(right==='settings'){const target=box(n,'Settings button','HORIZONTAL',44,0,null,11);icon(target,'settings','accent',22);links.push([target,'Data & settings']);}else if(right){const t=await text(n,right,'subhead','accent');if(right==='Save')links.push([t,'Queue']);}if(title)await text(c,title,'large');}
async function tabs(f,active){const bar=box(f,'Tab bar','HORIZONTAL',393,8,'surface',12);bar.primaryAxisAlignItems='CENTER';for(const [key,name]of [['Queue','package'],['Waiting','clock'],['History','history']]){const t=box(bar,key,'VERTICAL',109,4,active===key?'tint':null,8,16);t.counterAxisAlignItems='CENTER';icon(t,name,active===key?'accent':'secondary');await text(t,key,'micro',active===key?'accent':'secondary');links.push([t,key]);}bar.paddingBottom=12;const home=box(f,'Home indicator','HORIZONTAL',393,0,'surface',8);home.primaryAxisAlignItems='CENTER';const pill=remember(figma.createRectangle());pill.resize(134,5);pill.cornerRadius=3;pill.fills=[paint('ink')];home.appendChild(pill);}
async function caption(c,copy,color='secondary'){return text(c,copy,'caption',color,353);}
async function group(c,copy){const r=box(c,copy,'HORIZONTAL',353,8);r.counterAxisAlignItems='CENTER';icon(r,'pin','secondary',16);await text(r,copy,'caption','secondary');}
const q=await phone('Queue','01  /  TO RETURN',0);await nav(q.c,null,'settings','Return Queue');const top=box(q.c,'Queue summary','HORIZONTAL',353,12);await text(top,'4 items to return','subhead','secondary',203);const add=use(top,'Secondary action',{'Action label':'+ Add return'});add.layoutSizingHorizontal='FIXED';add.resize(138,44);links.push([add,'Add return']);q.c.itemSpacing=8;
await group(q.c,'UPS Store — Market St');for(const [item,merchant,date,amount]of [['USB-C dock','Amazon','Return by Oct 5','Expected $39.99'],['Running shoes','Target','Return by Oct 6','Expected $79.99']]){const card=use(q.c,'Return card',{'Item name':item,'Merchant':merchant,'Return date':date,'Expected amount':amount});if(item==='Running shoes')links.push([card,'Return details']);}
await group(q.c,'Target — Westgate');const late=use(q.c,'Return card',{'Item name':'Linen shirt','Merchant':'Target','Return date':'Oct 2 · Past your entered date','Expected amount':'Expected $34.00'});const lateText=late.findAllWithCriteria({types:['TEXT']}).find(t=>t.characters.includes('Past'));lateText.fills=[paint('warning')];await group(q.c,'Location not set');use(q.c,'Return card',{'Item name':'Desk lamp','Merchant':'Walmart','Return date':'Return date not set','Expected amount':'Expected amount not set'});await tabs(q.f,'Queue');
const a=await phone('Add return','02  /  ADD A RETURN',0);await nav(a.c,'Cancel','Save','Add return');await caption(a.c,'Start with the item and where you bought it.');use(a.c,'Field',{'Field label':'Item name','Field value':'USB-C dock'});use(a.c,'Field',{'Field label':'Merchant','Field value':'Amazon'});const opt=box(a.c,'Optional details','VERTICAL',353,16,'surface',16,20);const optr=box(opt,'Optional details heading','HORIZONTAL',321,12);await text(optr,'Optional details','strong','ink',281);icon(optr,'chevron','secondary',18);await text(opt,'Location, dates, amounts and notes','caption','secondary',321);await caption(a.c,'Only item name and merchant are required.');const addNote=box(a.c,'Add note','VERTICAL',353,8,'tint',20,20);icon(addNote,'package','accent',28);await text(addNote,'A small habit. One less loose end.','heading','ink',313);await text(addNote,'Add the details you know. You can fill in the rest later.','body','secondary',313);await tabs(a.f,'Queue');
const d=await phone('Return details','03  /  RETURN DETAILS',0);d.c.itemSpacing=8;await nav(d.c,'Queue','Edit','Running shoes');await caption(d.c,'Target · To return','accent');const where=box(d.c,'Drop-off location','HORIZONTAL',353,12,'surface',16,20);icon(where,'pin','accent',24);const whereText=box(where,'Location labels','VERTICAL',285,4);await text(whereText,'UPS Store — Market St','strong','ink',285);await text(whereText,'Drop-off location','caption','secondary');const det=box(d.c,'Return information','VERTICAL',353,4);for(const [l,v]of [['Return by','Oct 6, 2026'],['Expected refund','$79.99'],['Purchase price','$89.99']])use(det,'Info row',{'Row label':l,'Row value':v});await caption(d.c,'Return date entered by you.');const note=box(d.c,'Notes','VERTICAL',353,4,'surface',12,20);await text(note,'Notes','caption','secondary');await text(note,'Return shipping may be deducted.','body','ink',321);const dropped=use(d.c,'Action',{'Action label':'Mark as dropped off'});links.push([dropped,'Waiting']);use(d.c,'Secondary action',{'Action label':'Keep item'});await caption(d.c,'Recording drop-off does not confirm merchant acceptance.');await tabs(d.f,'Queue');
const w=await phone('Waiting','04  /  WAITING FOR REFUND',0);await nav(w.c,null,'settings','Waiting for refund');await caption(w.c,'2 returns · Add reimbursements as they arrive.');for(const [item,merchant,date,money,credit,expected,diff]of [['Denim jacket','Nordstrom','Dropped off Sep 28','$50.00','$30.00','$100.00','$20.00'],['Coffee grinder','Amazon','Dropped off Sep 30','$30.00','$0.00','Not set',null]]){const card=box(w.c,item,'VERTICAL',353,12,'surface',16,20);const title=box(card,'Item title','HORIZONTAL',321,8);await text(title,item,'heading','ink',283);icon(title,'chevron','secondary',18);await text(card,merchant+' · '+date,'caption','secondary',321);const sums=box(card,'Recorded amounts','HORIZONTAL',321,12);for(const [kind,value]of [['Money received',money],['Store credit',credit]]){const col=box(sums,kind,'VERTICAL',154,4,null,0);await text(col,kind,'caption','secondary');await text(col,value,'heading');}await text(card,'Expected refund: '+expected,'caption','secondary');if(diff)await text(card,'Difference from expected: '+diff,'caption','accent');else await text(card,'Expected amount not set.','caption','secondary');if(item==='Denim jacket')links.push([card,'Refund details']);}await caption(w.c,'Your manual records. No bank connection.');await tabs(w.f,'Waiting');
const r=await phone('Refund details','05  /  RECORDS & DIFFERENCE',1);r.c.itemSpacing=8;await nav(r.c,'Waiting','Edit','Denim jacket');await caption(r.c,'Nordstrom · Dropped off Sep 28','accent');const sum=box(r.c,'Refund summary','VERTICAL',353,4,'surface',12,20);for(const[l,v]of [['Expected refund','$100.00'],['Money received','$50.00'],['Store credit','$30.00']]){const row=box(sum,l,'HORIZONTAL',321,8);await text(row,l,'subhead','secondary',212);await text(row,v,'strong');}const diff=box(sum,'Difference','HORIZONTAL',321,8,'tint',12,12);await text(diff,'Difference','subhead','accent',188);await text(diff,'$20.00','strong','accent');await text(sum,"Based on amounts you've recorded.",'caption','secondary',321);await text(r.c,'Recorded reimbursements','subhead','secondary');use(r.c,'Reimbursement',{'Reimbursement type':'Money','Reimbursement amount':'$50.00','Reimbursement date':'Sep 30, 2026 · Tap to edit'});const cr=use(r.c,'Reimbursement',{'Reimbursement type':'Store credit','Reimbursement amount':'$30.00','Reimbursement date':'Oct 2, 2026 · Tap to edit'});const creditIcon=cr.findOne(n=>n.name==='Icon/money');creditIcon.visible=false;const record=use(r.c,'Action',{'Action label':'Record reimbursement'});links.push([record,'Record reimbursement']);use(r.c,'Secondary action',{'Action label':'Close return'});await tabs(r.f,'Waiting');
const h=await phone('History','06  /  HISTORY',1);await nav(h.c,null,'settings','History');await caption(h.c,'4 returns · Your completed records.');for(const[item,merchant,outcome,amount]of [['Duvet cover','Target · Closed Oct 2','Refund received','$50.00 money + $50.00 store credit'],['Travel bag','REI · Closed Oct 1','Partial refund','$80.00 money · $20.00 difference'],['Wireless mouse','Amazon · Closed Sep 29','Denied','No reimbursements recorded'],['Water bottle','Target · Closed Sep 27','Keeping item','No reimbursements recorded']]){const card=use(h.c,'History card',{'History item':item,'History merchant':merchant,'History outcome':outcome,'History amounts':amount});if(outcome==='Denied'){const tt=card.findAllWithCriteria({types:['TEXT']}).find(t=>t.characters==='Denied');tt.fills=[paint('secondary')];}}await tabs(h.f,'History');
const s=await phone('Data & settings','07  /  YOUR DATA',1);s.c.itemSpacing=8;await nav(s.c,'Queue',null,'Data & settings');const privacy=box(s.c,'Local data','HORIZONTAL',353,12,'surface',12,20);icon(privacy,'shield','accent',24);await text(privacy,'Stored on this iPhone. No account or sync.','body','secondary',285);const exportBtn=use(s.c,'Action',{'Action label':'Export backup'});use(s.c,'Secondary action',{'Action label':'Restore backup'});await caption(s.c,'Backups may contain purchase details and personal information.');const preview=box(s.c,'Restore preview','VERTICAL',353,8,'surface',16,20);await text(preview,'Restore preview','strong');await text(preview,'10 returns · 6 reimbursements','subhead','secondary');await text(preview,'This replaces the returns currently on this iPhone.','body','ink',321);await text(preview,'Export current backup','subhead','accent');await text(preview,'Replace current data','subhead','danger');await text(preview,'Cancel','subhead','secondary');const deleteButton=box(s.c,'Delete all data','HORIZONTAL',353,8,null,12);icon(deleteButton,'trash','danger',20);await text(deleteButton,'Delete all data','subhead','danger');await tabs(s.f,'Queue');
const m=await phone('Record reimbursement','08  /  RECORD REIMBURSEMENT',1);m.c.itemSpacing=8;await nav(m.c,'Cancel','Save');await text(m.c,'Record reimbursement','title','ink',353);await caption(m.c,'Denim jacket · Nordstrom');const types=box(m.c,'Reimbursement type','HORIZONTAL',353,4,'line',4,16);for(const[name,on]of [['Money',true],['Store credit',false]]){const part=box(types,name,'HORIZONTAL',170,8,on?'surface':null,12,12);part.primaryAxisAlignItems='CENTER';icon(part,on?'money':'credit',on?'accent':'secondary',20);await text(part,name,'subhead',on?'accent':'secondary');}use(m.c,'Field',{'Field label':'Amount (USD)','Field value':'$50.00'});use(m.c,'Field',{'Field label':'Date received','Field value':'Oct 3, 2026'});use(m.c,'Field',{'Field label':'Note (optional)','Field value':'Add a note'});const disclaimer=box(m.c,'Manual entry','VERTICAL',353,8,'tint',16,20);await text(disclaimer,'Record what you received.','strong','ink',321);await text(disclaimer,'Choose Money for cash refunds or Store credit for credit from the merchant.','subhead','secondary',321);const saveReimbursement=use(m.c,'Action',{'Action label':'Save reimbursement'});links.push([saveReimbursement,'Refund details']);await caption(m.c,'You can edit or delete this entry later.');await tabs(m.f,'Waiting');
await text(board,'P1 · No account, ads or payments · Photos and reminders come later','caption','secondary');
// Navigation links are left as intent metadata; this board is a static visual mockup.
figma.viewport.scrollAndZoomIntoView([board]);
const descendants=board.findAll(()=>true), counts={};for(const n of descendants)counts[n.type]=(counts[n.type]||0)+1;
const imageNodes=descendants.filter(n=>'fills'in n&&Array.isArray(n.fills)&&n.fills.some(p=>p.type==='IMAGE')).map(n=>({id:n.id,name:n.name,type:n.type,width:n.width,height:n.height}));
return {createdNodeIds:[...new Set(created)],pageId:page.id,board:{id:board.id,width:board.width,height:board.height},libraryId:library.id,collectionId:collection.id,variables:Object.fromEntries(Object.entries(vars).map(([k,v])=>[k,v.id])),styles:Object.fromEntries(Object.entries(styles).map(([k,v])=>[k,v.id])),components:Object.fromEntries(Object.entries(components).map(([k,v])=>[k,v.id])),screens:Object.fromEntries(Object.entries(screens).map(([k,v])=>[k,{id:v.id,width:v.width,height:v.height}])),counts,imageNodes,fontFamilies:[...new Set(descendants.filter(n=>n.type==='TEXT').map(n=>n.fontName.family))],plannedLinks:links.length,interactive:false};
