// Extend the verified editable board with P2 Summary, Settings and item reminders.
await figma.setCurrentPageAsync(await figma.getNodeByIdAsync('0:1'));
await Promise.all(['Regular','Medium','Semibold','Bold'].map(style=>figma.loadFontAsync({family:'SF Pro',style})));
const board=await figma.getNodeByIdAsync('11:93'), library=await figma.getNodeByIdAsync('11:49');
if(board.findOne(n=>n.name==='Summary'))throw new Error('P2 screens already exist; inspect before updating.');
const created=[],mutated=[],mark=n=>(created.push(n.id),n);
const variables=await figma.variables.getLocalVariablesAsync(),vars=Object.fromEntries(variables.map(v=>[v.name,v]));
const styles=Object.fromEntries((await figma.getLocalTextStylesAsync()).map(s=>[s.name.split('/').pop(),s]));
const paint=name=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:.5,g:.5,b:.5}},'color',vars['color/'+name]);
function box(parent,name,direction='VERTICAL',width=353,gap=8,fill=null,pad=0,radius=0){const n=mark(figma.createAutoLayout(direction));n.name=name;n.fills=fill?[paint(fill)]:[];n.resize(width,1);n.primaryAxisSizingMode=direction==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=direction==='VERTICAL'?'FIXED':'AUTO';n.itemSpacing=gap;if(vars['spacing/'+gap])n.setBoundVariable('itemSpacing',vars['spacing/'+gap]);for(const p of ['paddingTop','paddingBottom','paddingLeft','paddingRight']){n[p]=pad;if(vars['spacing/'+pad])n.setBoundVariable(p,vars['spacing/'+pad]);}if(radius){n.cornerRadius=radius;if(vars['radius/'+radius])n.setBoundVariable('cornerRadius',vars['radius/'+radius]);}parent.appendChild(n);return n;}
async function text(parent,copy,role='body',color='ink',width=null){const n=mark(figma.createText());n.name=copy;n.fontName=styles[role].fontName;await n.setTextStyleIdAsync(styles[role].id);n.characters=copy;n.fills=[paint(color)];n.textAutoResize=width?'HEIGHT':'WIDTH_AND_HEIGHT';if(width)n.resize(width,n.height);parent.appendChild(n);return n;}
const components=Object.fromEntries((await figma.getNodeByIdAsync('11:49')).findAllWithCriteria({types:['COMPONENT']}).map(n=>[n.name.split('/').pop(),n]));
function use(parent,name,values={}){const c=components[name],n=mark(c.createInstance());parent.appendChild(n);n.name=name;n.layoutSizingHorizontal='FILL';const definitions=c.componentPropertyDefinitions,settings={};for(const[k,v]of Object.entries(values)){const p=Object.keys(definitions).find(x=>x===k||x.startsWith(k+'#'));if(!p)throw new Error('Property missing: '+k);settings[p]=v;}n.setProperties(settings);created.push(...n.findAll(()=>true).map(d=>d.id));return n;}
function svg(parent,name,markup,width=22,height=22){const n=mark(figma.createNodeFromSvg('<svg width="'+width+'" height="'+height+'" viewBox="0 0 '+width+' '+height+'" xmlns="http://www.w3.org/2000/svg">'+markup+'</svg>'));n.name=name;parent.appendChild(n);created.push(...n.findAll(()=>true).map(d=>d.id));return n;}
function chartIcon(parent,color='#5D6880'){return svg(parent,'Icon/summary','<g fill="none" stroke="'+color+'" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v16h16M7 15v-4m4 4V7m4 8V4"/></g>');}
// Use the established component pattern: one editable switch source, repeated instances.
const toggleFrame=box(library,'Reminder switch','HORIZONTAL',353,12,'surface',16,20);toggleFrame.counterAxisAlignItems='CENTER';const toggleLabel=await text(toggleFrame,'Reminder label','strong','ink',257);svg(toggleFrame,'Switch/on','<rect x="0" y="0" width="52" height="32" rx="16" fill="#23755A"/><circle cx="36" cy="16" r="13" fill="#FFFFFF"/>',52,32);
const toggle=mark(figma.createComponentFromNode(toggleFrame));toggle.name='Return Queue/Reminder switch';toggle.description='P2 opt-in reminder switch shown enabled in the demo. No device permission is changed by the design.';const toggleProperty=toggle.addComponentProperty('Reminder label','TEXT','Return reminders');toggleLabel.componentPropertyReferences={characters:toggleProperty};components['Reminder switch']=toggle;
const oldBars=board.findAllWithCriteria({types:['FRAME']}).filter(n=>n.name==='Tab bar');
for(const bar of oldBars){for(const part of bar.children){part.resize(86.25,57);part.primaryAxisSizingMode='AUTO';part.counterAxisSizingMode='FIXED';mutated.push(part.id);}const summary=box(bar,'Summary','VERTICAL',86.25,4,null,8,16);summary.counterAxisAlignItems='CENTER';chartIcon(summary);await text(summary,'Summary','micro','secondary');bar.resize(393,81);bar.primaryAxisSizingMode='FIXED';bar.counterAxisSizingMode='FIXED';mutated.push(bar.id);}
const row=box(board,'03 / P2 — Summary and reminders','HORIZONTAL',1704,32);board.insertChild(board.children.length-2,row);
const screens={};
async function phone(key,label){const cell=box(row,label,'VERTICAL',393,12);await text(cell,label,'micro','secondary');const f=box(cell,key,'VERTICAL',393,0,'background');f.resize(393,852);f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';f.cornerRadius=40;f.clipsContent=true;f.strokes=[paint('line')];f.strokeWeight=1;f.effects=[{type:'DROP_SHADOW',color:{r:.07,g:.12,b:.25,a:.09},offset:{x:0,y:10},radius:24,spread:0,visible:true,blendMode:'NORMAL'}];screens[key]=f;use(f,'Status bar');const c=box(f,'Content','VERTICAL',393,8,null,20);c.paddingTop=0;c.paddingBottom=16;c.layoutSizingVertical='FILL';const bar=mark(oldBars[0].clone());f.appendChild(bar);created.push(...bar.findAll(()=>true).map(n=>n.id));for(const part of bar.children){part.fills=key==='Summary'&&part.name==='Summary'?[paint('tint')]:[];for(const t of part.findAllWithCriteria({types:['TEXT']}))t.fills=[paint(key==='Summary'&&part.name==='Summary'?'accent':'secondary')];for(const v of part.findAllWithCriteria({types:['VECTOR']})){if(Array.isArray(v.strokes))v.strokes=v.strokes.map(p=>p.type==='SOLID'?figma.variables.setBoundVariableForPaint(p,'color',vars['color/'+(key==='Summary'&&part.name==='Summary'?'accent':'secondary')]):p);}}const home=mark((await figma.getNodeByIdAsync('11:190')).clone());f.appendChild(home);created.push(...home.findAll(()=>true).map(n=>n.id));return{f,c};}
async function nav(c,left,title){const n=box(c,'Navigation','HORIZONTAL',353,0);n.resize(353,44);n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';n.primaryAxisAlignItems='SPACE_BETWEEN';n.counterAxisAlignItems='CENTER';await text(n,'‹  '+left,'subhead','accent');await text(n,'','subhead');await text(c,title,'large');}
const summary=await phone('Summary','09 / SUMMARY · P2');await nav(summary.c,'Queue','Summary');
const period=box(summary.c,'Period','HORIZONTAL',353,4,'line',4,16);for(const[label,active]of[['This month',false],['All time',true]]){const p=box(period,label,'HORIZONTAL',170.5,0,active?'surface':null,12,12);p.primaryAxisAlignItems='CENTER';await text(p,label,'subhead',active?'accent':'secondary');}
const money=box(summary.c,'Money received','VERTICAL',353,8,'surface',20,20);await text(money,'Money received','subhead','secondary');await text(money,'$210.00','large','accent');await text(money,'Recorded cash refunds','caption','secondary');
const credit=box(summary.c,'Store credit total','HORIZONTAL',353,8,'surface',16,20);credit.primaryAxisAlignItems='SPACE_BETWEEN';credit.counterAxisAlignItems='CENTER';await text(credit,'Store credit','strong');await text(credit,'$80.00','title');
use(summary.c,'Info row',{'Row label':'Returns reimbursed','Row value':'4'});await text(summary.c,'6 recorded reimbursements · All time','caption','secondary',353);
const month=box(summary.c,'This month snapshot','VERTICAL',353,8,'tint',16,20);await text(month,'This month · October 2026','subhead','accent');const mc=box(month,'Month amounts','HORIZONTAL',321,12);for(const[k,v]of[['Money','$160.00'],['Store credit','$80.00']]){const col=box(mc,k,'VERTICAL',154.5,4);await text(col,k,'caption','secondary');await text(col,v,'heading');}await text(month,'4 returns with reimbursements','caption','secondary');await text(summary.c,'Only recorded reimbursements count. Expected refunds are shown separately in each return.','caption','secondary',353);
const settings=await phone('Settings','10 / SETTINGS · P2');await nav(settings.c,'Queue','Settings');await text(settings.c,'Preferences for this iPhone','caption','secondary');use(settings.c,'Reminder switch',{'Reminder label':'Return reminders'});use(settings.c,'Info row',{'Row label':'Device permission','Row value':'Allowed'});await text(settings.c,'Default timing','subhead','secondary');use(settings.c,'Field',{'Field label':'Remind me','Field value':'1 day before the return date'});use(settings.c,'Field',{'Field label':'Time','Field value':'9:00 AM · local time'});await text(settings.c,'Choose reminders for each return. A return date is needed for a drop-off reminder.','caption','secondary',353);use(settings.c,'Secondary action',{'Action label':'Data & backups'});await text(settings.c,'No account or sync. Lock-screen messages hide the item, merchant and amount.','caption','secondary',353);
const reminder=await phone('Item reminder','11 / ITEM REMINDER · P2');await nav(reminder.c,'Return details','Reminder');await text(reminder.c,'Running shoes · Target','subhead','secondary');use(reminder.c,'Field',{'Field label':'Return by · entered by you','Field value':'Oct 6, 2026'});use(reminder.c,'Reminder switch',{'Reminder label':'Remind me'});const timing=box(reminder.c,'Reminder timing','VERTICAL',353,4);use(timing,'Info row',{'Row label':'Remind me','Row value':'1 day before'});use(timing,'Info row',{'Row label':'Time','Row value':'9:00 AM'});const planned=box(reminder.c,'Planned reminder','VERTICAL',353,8,'tint',12,20);await text(planned,'Planned reminder','caption','accent');await text(planned,'Oct 5, 2026 · 9:00 AM','heading');await text(planned,'Running shoes · Target\nDrop off at UPS Store — Market St','caption','secondary',329);use(reminder.c,'Action',{'Action label':'Save reminder'});await text(reminder.c,'Drop-off cancels this reminder. Refund check-ins can be scheduled separately.','caption','secondary',353);
const detail=await figma.getNodeByIdAsync('11:247');const link=use(detail,'Secondary action',{'Action label':'Reminder · Oct 5 at 9 AM'});detail.insertChild(detail.children.length-2,link);mutated.push(detail.id);
const data=await figma.getNodeByIdAsync('11:481');data.name='Data & backups';mutated.push(data.id);const dataTitle=data.findAllWithCriteria({types:['TEXT']}).find(n=>n.characters==='Data & settings');dataTitle.characters='Data & backups';dataTitle.name=dataTitle.characters;mutated.push(dataTitle.id);
const back=await figma.getNodeByIdAsync('11:490');back.characters='Settings';back.name='Settings';mutated.push(back.id);const backSlot=await figma.getNodeByIdAsync('11:487');backSlot.resize(90,44);mutated.push(backSlot.id);
const footer=await figma.getNodeByIdAsync('11:587');footer.characters='P1 workflow + P2 concepts · Summary and reminders are design previews · No account, ads or payments';footer.name=footer.characters;mutated.push(footer.id);board.name='Return Queue / Prototype v2';mutated.push(board.id);
const nodes=board.findAll(()=>true);return{createdNodeIds:[...new Set(created)],mutatedNodeIds:mutated,board:{id:board.id,width:board.width,height:board.height},newScreens:Object.fromEntries(Object.entries(screens).map(([k,v])=>[k,{id:v.id,width:v.width,height:v.height}])),newComponent:{id:toggle.id,name:toggle.name},counts:nodes.reduce((o,n)=>(o[n.type]=(o[n.type]||0)+1,o),{}),fontFamilies:[...new Set(nodes.filter(n=>n.type==='TEXT').map(n=>n.fontName.family))],imageNodes:nodes.filter(n=>'fills'in n&&Array.isArray(n.fills)&&n.fills.some(p=>p.type==='IMAGE')).map(n=>({id:n.id,name:n.name,type:n.type,width:n.width,height:n.height})),bounds:board.findAllWithCriteria({types:['FRAME']}).filter(n=>n.name==='Content').map(n=>({screen:n.parent.name,height:n.height,bottom:Math.max(...n.children.map(c=>c.y+c.height))}))};
